### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yuche** [yuche/vue-strap#41]
## Nov 20, 2015
- [ ] Vue v1.x support.
- [ ] Tabs components bug. #34 
- [ ] A collapse component. #21  
- [ ] More modal controls. #19 #37 
- [ ] CI and better dev tools.

## Nov 30, 2015
- [ ] Search for select component.
- [ ] Localization for datepicker component.
- [ ] Refactor tooltip and popover components.
- [ ] Refactor dropdown component.
- [ ] A new Slider component.
- [ ] A new timepicker components. #26 

## Dec 10, 2015
- [ ]  JSFIDDLE live edit on documents.

## Dec 30, 2015
- [ ] Tests.

Sorry for the delay. I was so busy for some company stuff in past few days.

**Comment by FerchoCarcho** [comment]
Thank you @yuche!! Very excpected Release.

**Comment by roblav96** [comment]
Sounds good! can't wait to see this updated.

**Comment by ghprod** [comment]
Waiting for 1.x support :+1: 

Thanks

**Comment by dingyiming** [comment]
`Thanks`

**Comment by zhangbihua** [comment]
amazing

**Comment by amanpatel** [comment]
I felt the need to mention that v1 support is being worked on in the v1 branch. Find more about it here:

https://github.com/yuche/vue-strap/tree/v1

Carousel and Slider components are not working as designed at the moment. This won't be a "drop-in" replacement for people with old codebases, as the syntax with which you use the components has changed.

**Comment by roblav96** [comment]
looking good!

**Comment by mstnorris** [comment]
@amanpatel thanks, I was going to ask.

**Comment by yuche** [comment]
With @amanpatel 's help, v1.x support now release

**Comment by FerchoCarcho** [comment]
Thank very much!! !! !!

**Comment by FerchoCarcho** [comment]
if I npm install vue-strap --save it says  "vue-strap": "^0.1.2"

**Comment by mstnorris** [comment]
@FerchoCarcho I don't think they've updated npm yet as I get the same result.

**Comment by FerchoCarcho** [comment]
txs, I will wait @mstnorris

**Comment by yuche** [comment]
@FerchoCarcho @mstnorris 
It should work now

**Comment by yuche** [comment]
@FerchoCarcho @mstnorris 
It should work now.

**Comment by mstnorris** [comment]
Cool, I just saw that npmjs.com has been updated! Thanks!

**Comment by FerchoCarcho** [comment]
thank you @yuche !!

**Comment by amanpatel** [comment]
@yuche I've started a bootstrap4 branch. The readme in that branch has information on the progress with migration. Surprisingly an awful lot of stuff works already without much changes, but there are quirks.

**Comment by mitjarogl** [comment]
:+1:

**Comment by smolinari** [comment]
:+1: for the v4! 

Scott

**Comment by qiancheng1203** [comment]
good,datatable

**Comment by kayyyy** [comment]
:+1:

**Comment by gamperl** [comment]
:+1:

**Comment by smolinari** [comment]
How hard or how much work will it be to change from v3 to v4, when it is out?

Scott

**Comment by amanpatel** [comment]
Timepicker component (very very basic) implemented in the boostrap4 branch. I can work on bringing it to main branch in case there are lot of people who need it.

**Comment by ablipan** [comment]
@amanpatel +1

**Comment by gamperl** [comment]
@amanpatel +1

**Comment by xiaokaike** [comment]
:+1:

**Comment by plakhin** [comment]
@amanpatel +1

**Comment by xiaolongyuan** [comment]
:+1:

**Comment by Jack614** [comment]
Thanks!!

**Comment by longdajiangjun** [comment]
can upgrade to vue2 ?

**Comment by ryanrca** [comment]
Roadmap for updating to Vue 2. 0?

**Comment by watonyweng** [comment]
Thank you @yuche

**Comment by 18979687252** [comment]
I want use this vue-strap files in my project,but i don't how to do it?

**Comment by poppabear8883** [comment]
Vue2 Please and thanks!

**Comment by eklem** [comment]
@poppabear8883, @wffranco has a [fork that is moving towards full VueJS v2 support](https://github.com/wffranco/vue-strap).

**Comment by poppabear8883** [comment]
i noticed this, and am working with it now, but having issues See issues @wffranco

**Comment by eklem** [comment]
A little patience, and I guess they will be fixed. Waiting for something too. After seeing the activity on @yuche's overview-page, I think that's the best bet.

**Comment by wffranco** [comment]
updated v2 with my last version

**Comment by LukaszWiktor** [comment]
@wffranco Thanks a lot! Keep up the good work 👍

**Comment by lijinbia** [comment]
谢谢大佬
